baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'Learning Go'
disqusShortname = ""
ignoreFiles = []
paginate = 25
enableRobotsTXT = true
summaryLength = 15
pluralizelisttitles = false

[Author]
  name = "Anonymous"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'

[taxonomies]
  category = "categories"

[permalinks]
  post = "/:section/:slug/"
  categories = "/:slug/"

[params]
  description = "A place to learn Go"
  footer = "&copy; [Boot.dev](https://boot.dev) {Year}"
  logo = "/favicons/favicon-32x32.png"
  googleTagManager = "GTM-PT7FHFB"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "hugo gen chromastyles --style=dracula > assets/css/syntax.css"
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
